apiVersion: v1
kind: Service
metadata:
  name: geodata-web-service
  namespace: geodata
  labels:
    app: geodata-web-service
spec:
  selector:
    app: geodata-app-pod
  ports:
    - name: http
      port: 8080