kind: Deployment
apiVersion: apps/v1
metadata:
  name: geodata-web-deployment
  namespace: geodata
  labels:
    app: geodata-web
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      deploy: geodata-web
  template:      
    metadata:
      labels:
        app: geodata-web
        deploy: geodata-web
    spec:
      containers:
        - name: geodata
          image: ag04/geodata-ng:latest
          imagePullPolicy: Always
          env:
          - name: GEODATA_API_URL
            value: "http://geodata-rest-service:8080/api"
          - name: GEODATA_MNGMT_URL
            value: "http://geodata-rest-service:8080/management"
          - name: GEODATA_SWAGGER_URL
            value: "http://geodata-rest-service:8080/swagger-resources"
          - name: GEODATA_AUTH_URL
            value: "http://geodata-rest-service:8081/auth"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: '64Mi'
              cpu: '200m'
            limits:
              memory: '128Mi'
              cpu: '500m'
