apiVersion: v1
kind: Secret
metadata:
  name: geodata-secret
  namespace: geodata
type: Opaque
data:
  geodata_db_pwd: {{ .Values.postgres.database.password | b64enc }}
  geodata_mail_pwd: {{ .Values.geodata.mail.password | b64enc }}