apiVersion: v1
kind: Service
metadata:
  name: geodata-rest-service
  namespace: geodata
  labels:
    app: geodata-rest-service
spec:
  selector:
    app: geodata-rest
  ports:
    - name: http
      port: 8080